micronaut:
    application:
        name: user-service

datasources:
    default:
        url: jdbc:postgresql://localhost:5000/user-db
        driverClassName: org.postgresql.Driver
        username: postgres
        password: postgres


jpa:
    default:
        packages-to-scan:
            - 'user.service.model'
        properties:
            hibernate:
                hbm2ddl:
                    auto: none
                show_sql: true

flyway:
    datasources:
        default:
            locations: classpath:db-migrations
